---
title: "Lista de Treinamento 1"
author: "Douglas Cardoso"
date: "9/11/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Q1 - Realize as seguintes operações no R e entenda o resultado:

(i) `r 4 * (2/5 - 7)`
(ii) `r 12 - (5800 * ((4 * 0.2) - 18 + (12 * 0.11)))`
(iii) `r (99/12) - (6726 * (56/0.293)) + 15`
(iv) `r ((42/17) * 256) - ((45 * 40.9 + 2) / (763 * 0.4))`
(v) `r ((56 - 0.1 * (12/-0.9))^(2*0.5+4)) / (32 - 4 * 0.6)`
(vi) `r ((12 * 8) - (0.5 * 7625)) / ((4 * 2) + (6 * 8) - 56)`
(vii) `r (56^(4-2*0.6)) * (12^(-12 * 0.227 - 1)) * (-0.762 / (9^(12*1-8)))`
(viii) `r 234 - ((12 - 4i) / (0.6 * 12 - 9))`

## Q2 - Crie os seguintes vetores e matrizes no R:

```{r}
# (i)
v <- c(-3, 4, 0.5, 12, 45)

# (ii)
u <- c(-0.1, -0.34, 93, 2, 1, 0, 4)

# (iii)
t <- c(8, -0.9, 10, 3, -1)

# (iv) 
p <- c(3, 4, -3, -4, 0, 1)

# (v)
X <- matrix(
  data = c(4, 2, -1, 13, -0.9, 5, 4, 2), 
  ncol = 4, nrow = 2, byrow = TRUE)

# (vi)
Z <- matrix(
  data = c(4, 2, 8, -1, -3, -7, 6, 0.4, -9, 10, 11, 12),
  ncol = 3, nrow = 4, byrow = TRUE) 
```